# Generated by Django 5.1.6 on 2025-02-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('chunk_index', models.IntegerField()),
                ('total_chunks', models.IntegerField()),
                ('chunk', models.FileField(upload_to='chunks/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.fileupload')),
            ],
            options={
                'unique_together': {('filename', 'chunk_index')},
            },
        ),
    ]
